#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

if [ -f core.conf ]; then
   mv core.conf /config
   rm /config/auth -f
fi

USERNAME=${USERNAME}
PASSWORD=${PASSWORD}
echo "$USERNAME:$PASSWORD:10" >/config/auth

echo '
-------------------------------------
Deluged by nickd25

Based on https://github.com/linuxserver/docker-deluge

-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /config
chown abc:abc /downloads

echo "
Deluge username: $USERNAME
Deluge Password: $PASSWORD"
